apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /hello
          backend:
            serviceName: hello-svc
            servicePort: 83
